# Generated by Django 3.2.21 on 2023-11-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/patient'),
        ),
    ]
